name: dxw_members_only
services:

  wordpress:
    image: thedxw/wpc-wordpress:php8.2
    ports:
      - "80:80"
    links:
      - mysql
    volumes:
      - ../:/usr/src/app
      - ../:/var/www/html/wp-content/plugins/dxw-members-only
      - ./uploads/:/var/www/html/wp-content/uploads
  mysql:
    image: mariadb:10
    ports:
      - "3306:3306"
    environment:
       MYSQL_ROOT_PASSWORD: foobar
       MYSQL_DATABASE: wordpress
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: