language: php
sudo: false
git:
  submodules: false
cache:
  directories:
    - vendor
php:
  - 7.0
install:
  - composer install
script:
  # - vendor/bin/peridot spec
  - vendor/bin/php-cs-fixer fix --dry-run -v --diff
