<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'phpseclib\\' => array($vendorDir . '/phpseclib/phpseclib/phpseclib'),
    'Missing\\' => array($vendorDir . '/dxw/php-missing/src'),
    'Dxw\\Result\\' => array($vendorDir . '/dxw/result/src'),
    'Dxw\\CIDR\\' => array($vendorDir . '/dxw/cidr/src'),
);
