<?php return array(
    'root' => array(
        'name' => '__root__',
        'pretty_version' => 'dev-master',
        'version' => 'dev-master',
        'reference' => '1a077ad87c0e1317215976adf344842a3b22af82',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => false,
    ),
    'versions' => array(
        '__root__' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '1a077ad87c0e1317215976adf344842a3b22af82',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'dxw/cidr' => array(
            'pretty_version' => 'v3.1.2',
            'version' => '3.1.2.0',
            'reference' => '9cb82cb70f0d4a4a32b1b2e3e1ae005fba84d581',
            'type' => 'library',
            'install_path' => __DIR__ . '/../dxw/cidr',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'dxw/php-missing' => array(
            'pretty_version' => 'v1.0.0',
            'version' => '1.0.0.0',
            'reference' => '544ce7df568f6296e3811454b0e1df79ceb498b7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../dxw/php-missing',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'dxw/result' => array(
            'pretty_version' => 'v1.0.4',
            'version' => '1.0.4.0',
            'reference' => '5b9d3988c215dc95e17cd082a33bc2c02b6007ca',
            'type' => 'library',
            'install_path' => __DIR__ . '/../dxw/result',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpseclib/phpseclib' => array(
            'pretty_version' => '2.0.38',
            'version' => '2.0.38.0',
            'reference' => 'b03536539f43a4f9aa33c4f0b2f3a1c752088fcd',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpseclib/phpseclib',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
