<?php return array(
    'root' => array(
        'pretty_version' => 'dev-master',
        'version' => 'dev-master',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'reference' => '9d3005eb310e99928f912b4720ae554e8117556c',
        'name' => '__root__',
        'dev' => false,
    ),
    'versions' => array(
        '__root__' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'reference' => '9d3005eb310e99928f912b4720ae554e8117556c',
            'dev_requirement' => false,
        ),
        'dxw/cidr' => array(
            'pretty_version' => 'v3.1.2',
            'version' => '3.1.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../dxw/cidr',
            'aliases' => array(),
            'reference' => '9cb82cb70f0d4a4a32b1b2e3e1ae005fba84d581',
            'dev_requirement' => false,
        ),
        'dxw/php-missing' => array(
            'pretty_version' => 'v1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../dxw/php-missing',
            'aliases' => array(),
            'reference' => '544ce7df568f6296e3811454b0e1df79ceb498b7',
            'dev_requirement' => false,
        ),
        'dxw/result' => array(
            'pretty_version' => 'v1.0.4',
            'version' => '1.0.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../dxw/result',
            'aliases' => array(),
            'reference' => '5b9d3988c215dc95e17cd082a33bc2c02b6007ca',
            'dev_requirement' => false,
        ),
        'phpseclib/phpseclib' => array(
            'pretty_version' => '2.0.34',
            'version' => '2.0.34.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpseclib/phpseclib',
            'aliases' => array(),
            'reference' => '98a6fe587f3481aea319eef7e656d02cfe1675ec',
            'dev_requirement' => false,
        ),
    ),
);
