<?php return array(
    'root' => array(
        'name' => '__root__',
        'pretty_version' => 'dev-master',
        'version' => 'dev-master',
        'reference' => 'cee9a23748572e0213965668ed0872ae13e47d5e',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => false,
    ),
    'versions' => array(
        '__root__' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => 'cee9a23748572e0213965668ed0872ae13e47d5e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'dxw/cidr' => array(
            'pretty_version' => 'v3.2.0',
            'version' => '3.2.0.0',
            'reference' => 'b07dd398f5a93441f57a687982bc7d0ffb96729a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../dxw/cidr',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'dxw/php-missing' => array(
            'pretty_version' => 'v1.0.0',
            'version' => '1.0.0.0',
            'reference' => '544ce7df568f6296e3811454b0e1df79ceb498b7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../dxw/php-missing',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'dxw/result' => array(
            'pretty_version' => 'v1.0.6',
            'version' => '1.0.6.0',
            'reference' => 'd554bb10f0cf74056ccd26526688e194652eef79',
            'type' => 'library',
            'install_path' => __DIR__ . '/../dxw/result',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpseclib/phpseclib' => array(
            'pretty_version' => '2.0.45',
            'version' => '2.0.45.0',
            'reference' => '28d8f438a0064c9de80857e3270d071495544640',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpseclib/phpseclib',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
