#!/bin/sh

# script/setup: Set up the application for the first time after cloning, or set
#               it back to the initial unused state.

set -e

script/test

script/server -d

# Wait for the MySQL container to be ready
while ! docker compose -f local/docker-compose.yml exec wordpress mysqladmin ping -hmysql -pfoobar --silent >/dev/null; do
	echo "===> Waiting for MySQL instance to be ready..."
	sleep 5
done

docker compose -f local/docker-compose.yml exec wordpress /usr/src/app/local/setup/internal.sh

npx playwright install --with-deps

echo "==> Running end-to-end tests..."
npx playwright test
