#!/bin/sh

# script/test: Run the test suite for the application.
set -e

cd "$(dirname "$0")/.."

if [ -n "$DEBUG" ]; then
  set -x
fi

echo "==> Updating..."
script/update

echo "==> Running php-cs-fixer..."
vendor/bin/php-cs-fixer fix --dry-run -v --diff

echo "==> Running static code analysis..."
vendor/bin/psalm --error-level=1 --find-unused-psalm-suppress --no-cache

if [ -z "$CI" ]; then
  echo "==> Running end-to-end tests..."
  npx playwright test
fi