on:
  pull_request:
  push:

jobs:
  tests:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        php-versions: ['8.3']
    steps:
      - uses: actions/checkout@v5
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: CI build & test
        run: script/cibuild
